version: 2
build:
  os: 'ubuntu-lts-latest'
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .

